### ISSUE TITLE
Can't resolve 'hastscript' 

### ISSUE THREAD

**Issue by danistefanovic** [wooorm/refractor#1]
```
./node_modules/refractor/core.js
Module not found: Can't resolve 'hastscript' in ...
```

The `hastscript` package needs to be moved from `devDependencies` to `dependencies` in the package.json file

**Comment by wooorm** [comment]
😱

Thanks for letting me know!

Would you be interested in creating a PR for that?

**Comment by wooorm** [comment]
@danistefanovic I responded super quick, so maybe you didn’t get the above. Friendly ping! 👋
