### ISSUE TITLE
TSX interprets TypeScript generic params as JSX tags

### ISSUE THREAD

**Issue by 1000hz** [wooorm/refractor#22]
It seems like TSX doesn't correctly differentiate TypeScript generic type parameters from JSX opening tags, as evidenced by the difference between these two examples:

![image](https://user-images.githubusercontent.com/1395018/60552910-79bf9f80-9cf6-11e9-8477-c5e8a45587c8.png)

![image](https://user-images.githubusercontent.com/1395018/60552943-95c34100-9cf6-11e9-83d8-aab1895f9093.png)

**Comment by wooorm** [comment]
refractor is a proxy for prism. Problems with how syntax highlighting is done can be reported at [Prism’s issues](https://github.com/PrismJS/prism)
