### ISSUE TITLE
Unexpected php highlight

### ISSUE THREAD

**Issue by dancerphil** [wooorm/refractor#23]
The result of refractor.highlight(...) is unexpected.

see demo: https://codesandbox.io/s/unexpected-php-highlight-9x2u4

**Comment by wooorm** [comment]
Seems to be related to placeholders:

https://github.com/wooorm/refractor/blob/48d2d90423f60cbb28c0779d6f85ec560ce572b6/lang/php.js#L121-L129

Not sure if we can fix the `after-tokenize` phase.

**Comment by wooorm** [comment]
I tracked this down to `css-extras`: 

https://github.com/wooorm/refractor/blob/32c65ffb2dea82f848cf675bdb689dcd09021e49/lang/css-extras.js#L79

And I can reproduce it with normal Prism as well:

<img width="1268" alt="Screenshot 2019-08-01 at 4 40 27 pm" src="https://user-images.githubusercontent.com/944406/62302776-34b89580-b47b-11e9-899a-5254b1cc0adb.png">

I’ll raise an issue there!

**Comment by wooorm** [comment]
I raised https://github.com/PrismJS/prism/issues/2008.
As this is an issue there, I don’t think it’s needed to keep it open here.
Follow their issue for updates, and when there’s a fix released, it’ll be pulled into refractor!
