### ISSUE TITLE
unexpect css-in-js highlight

### ISSUE THREAD

**Issue by dancerphil** [wooorm/refractor#25]
Affect only `refractor@2.10.0`

see demo: https://codesandbox.io/s/unexpected-css-in-js-highlight-hd5hi

Not sure if it is relevant to #23

**Comment by wooorm** [comment]
Probably related to GH-23, so best to raise it with Prism.

**Comment by dancerphil** [comment]
Some extra information:

#23 happens in `refractor@2.9.0` & `refractor@2.10.0` while this happens in `refractor@2.10.0` only.

**Comment by wooorm** [comment]
Did you open an issue at Prism?

**Comment by wooorm** [comment]
This is an issue with Prism, not with refractor, therefore I’m closing this as there is no need to track it in two places.
