### ISSUE TITLE
highlighting specific lines

### ISSUE THREAD

**Issue by timsuchanek** [wooorm/refractor#3]
Hey, how would you highlight specific lines with refractor?
Would you use the [prism.js plugin](http://prismjs.com/plugins/line-highlight/) for that?
Thanks!

**Comment by wooorm** [comment]
I don’t know! [Prism plugins probably won’t work](https://github.com/wooorm/refractor#plugins).

You can work with the [AST](https://github.com/syntax-tree/hast#ast) though?

**Comment by wooorm** [comment]
Let me know by commenting below if you’d still like to discuss this.

**Comment by karlhorky** [comment]
For anyone looking for this for either [`refractor`](https://github.com/wooorm/refractor) or [`lowlight`](https://github.com/wooorm/lowlight), Conor Hastings did an implementation of this for these libraries in `react-syntax-highlighter`: https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/46
