### ISSUE TITLE
Change prismjs to carat range?

### ISSUE THREAD

**Issue by karlhorky** [wooorm/refractor#33]
Hi @wooorm !

Maybe going forward, you would consider changing to a carat version range for `prismjs`? 

It would help a lot for projects stuck with older dependencies which have `refractor` as a transitive dep (especially when things like [security vulnerabilities with `prismjs`](https://github.com/advisories/GHSA-wvhm-4hhf-97x9) happen).

Anyway, thanks for the consideration!

**Comment by wooorm** [comment]
Hi Karl! 👋

We have Prism as a dep [for its core](https://github.com/wooorm/refractor/blob/b73904de955e3961e981aa37aadf79356dee3740/core.js#L22). Basically hidden internals. Loosening the range will cause stuff to break. I find preventing everything from exploding more important than older dependencies. Refractor also has a track record of updating fast after Prism updates, and if you use refractor itself with a loose range, you’ll also get Prism updates.

The security vulnerability did not affect anyone using refractor, as we don’t support plugins. If there is an issue, it’s with Dependabot falsely claiming there was one 🤷‍♂️

**Comment by karlhorky** [comment]
Ok, understandable. Thanks for the answer :)

**Comment by wooorm** [comment]
No problem, thanks for understanding!
