### ISSUE TITLE
Bug: Can we change global to globalThis?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [wooorm/refractor#36]
https://github.com/wooorm/refractor/blob/0e49fc33bfac9ae201a815a1e33b3a53152cf73a/core.js#L221

In browsers we have no `global`, but we have `globalThis`  both in browsers and nodejs

**Comment by wooorm** [comment]
Did you run into an error?

**Comment by xiaoxiangmoe** [comment]
Yes!

**Comment by wooorm** [comment]
Hmm. Do you know if angular/cli is using webpack 5 now?

This line has been in there since the beginning, millions of users have used it just fine, so I’m assuming bundlers have always added it, but also know that webpack 5 changed some similar things.

**Comment by xiaoxiangmoe** [comment]
No, angular/cli use webpack 4. Maybe we should support webpack 5, also.

**Comment by wooorm** [comment]
In that case, I’m assuming this still works fine in webpack 5 (because that’s been out a bit and nobody else raised an issue for it), but that angular/cli is the root problem.

Regardless, I’d appreciate a PR!

**Comment by xiaoxiangmoe** [comment]
OK, I'll create a PR to change global to globalThis. 😊

**Comment by wooorm** [comment]
Oh btw, sorry I forgot: I’m not sure `globalThis` is a good idea. As it doesn’t work everywhere, and that could be a breaking change.

I think we’re already getting the global scope somewhere else in the code. Perhaps use that?

**Comment by xiaoxiangmoe** [comment]
https://github.com/wooorm/refractor/blob/0e49fc33bfac9ae201a815a1e33b3a53152cf73a/core.js#L9-L14

Do you mean we should use `ctx`？

**Comment by wooorm** [comment]
I think that’d do the trick yeah. But maybe that’d also need to support Node’s `global`?

**Comment by xiaoxiangmoe** [comment]
see https://github.com/wooorm/refractor/pull/37

**Comment by xiaoxiangmoe** [comment]
Another polyfill for globalThis: https://github.com/ungap/global-this/blob/master/index.js
