### ISSUE TITLE
Incorrect global in jsdom environment

### ISSUE THREAD

**Issue by rexxars** [wooorm/refractor#38]
After  #37 was merged I appear to have some issues where prismjs thinks the global is one thing, while refractor thinks it's a different thing. This results in `Prism.manual` not being set, which makes prism attach events to the DOMReady events and such.

I'm not quite sure what the right solution is - I'll see if I can come up with a reproducible test case.

**Comment by wooorm** [comment]
Hmm annoying, sorry, thanks for investigating!

/cc @xiaoxiangmoe on this

**Comment by xiaoxiangmoe** [comment]
@rexxars Can you give me a minimal demo of this?

**Comment by wooorm** [comment]
Friendly ping @rexxars!

**Comment by wooorm** [comment]
Closing this for now as not actionable. If this is still an issue and can be solved here, I’d appreciate a reproduction!
