### ISSUE TITLE
Prism is running on page load

### ISSUE THREAD

**Issue by tamagokun** [wooorm/refractor#4]
when the page loads, it seems like Prism gets run across the entire page. Is there a way to work around this?

**Comment by tamagokun** [comment]
Seems like if it gets loaded in page, it will run "highlightAll" unless Prism.manual is set to true.

https://github.com/PrismJS/prism/blob/gh-pages/components/prism-core.js#L505-L522

**Comment by wooorm** [comment]
So, from what I’m reading, we must set `window.Prism = {manual: true}` to turn this off?

Would you be interested in a tested PR for this?

**Comment by tamagokun** [comment]
totally. PR coming up.
