### ISSUE TITLE
Backporting Prism 1.24 to v3 for security fix?

### ISSUE THREAD

**Issue by mayank99** [wooorm/refractor#41]
See high severity vulnerability: https://github.com/advisories/GHSA-gj77-59wh-66hg

Because refractor@3 uses `~1.23.0` instead of `^`, users need to force resolve to the patched version (I know this is a mild inconvenience, so feel free to close this issue).

**Comment by wooorm** [comment]
Not sure why Prism didn’t release it in a patch. But, released.
