### ISSUE TITLE
markdown code-block using docuemnt

### ISSUE THREAD

**Issue by dancerphil** [wooorm/refractor#43]
We are using refractor in web worker.

It turns out that `code-block` in markdown will fail since we don't have `document` in web worker.

It could be better if we have a `document` check.

Related code: https://github.com/wooorm/refractor/blob/main/lang/markdown.js#L367

Version: refractor@3.4.0 (I think also in 4.1.0)

**Comment by wooorm** [comment]
I don’t understand the question.

The code you link to never runs, because `Prism.plugins.autoloader` shouldn’t be true.

Please spend time framing your question or post reproduction code to show that it’s a bug
