### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by karlhorky** [wooorm/refractor#46]
Hi @wooorm 👋

What are your thoughts on adding a link to an interactive demo to the readme?

I've made so many demo repls on Replit for refractor when I needed to debug something - would be cool to be able to just click on the existing demo and modify some things!

**Comment by wooorm** [comment]
Do you mean a demo as in a small custom website? What would you think of forkable runkit / replit / codesandboxes?

**Comment by karlhorky** [comment]
Yeah I meant more like an interactive playground like Replit. Eg. just set this one up now:

https://replit.com/@karlhorky/refractor-demo

**Comment by karlhorky** [comment]
Maybe also including the HTML version, to make it easier to visually parse what's going on there...

**Comment by wooorm** [comment]
Yeah I’m open to a link to something like that!

**Comment by karlhorky** [comment]
Ok, open at #50, happy to take feedback and changes over there
