### ISSUE TITLE
sideEffects: false incorrect

### ISSUE THREAD

**Issue by pfgithub** [wooorm/refractor#48]
all.js and common.js have side effects that get deleted when tree-shaking because of this option in package.json

**Comment by wooorm** [comment]
which parts?

**Comment by pfgithub** [comment]
all.js and common.js remove all their language imports and end up registering nothing except plaintext. I think the correct option for sideEffects is

```json
"sideEffects": ["lib/all.js", "lib/common.js"],
```

**Comment by wooorm** [comment]
Could you check by changing the `package.json` in your `node_modules` locally which configuration works for your bundler (and share what bundler that is)?
I’m up for changing this but I’d appreciate publishing something more certain than an “I think X will work”!

**Comment by pfgithub** [comment]
It works with `"sideEffects": ["lib/all.js", "lib/common.js"],`. I tested and

- the bundle size is large, as expected, rather than being tiny
- getLanguages returns the full language list
- languages seem to work.

**Comment by wooorm** [comment]
Could you clarify which bundler that is?

**Comment by pfgithub** [comment]
I'm using vite which uses rollup internally

**Comment by wooorm** [comment]
released!
