### ISSUE TITLE
Language "txt" or "empty"

### ISSUE THREAD

**Issue by Hurtak** [wooorm/refractor#49]
It would be great if refactor supported empty or "txt" language settings that would do no highlight. I have a https://github.com/rexxars/react-refractor component for code highlight in my blog, and sometimes it is just some pseudocode that I do not want any hightlight, but I want the code block to have the same styles as other code blocks.

Is there some way to do that? Or perhaps https://github.com/rexxars/react-refractor is better place to create the issue?

**Comment by wooorm** [comment]
I understand the use case but I don’t think it makes sense here. This project tries to mimic Prism.

In `rehype-highlight` I added a `plainText` option: https://github.com/rehypejs/rehype-highlight#optionsplaintext. So maybe that’s something for `react-refractor` too?

**Comment by Hurtak** [comment]
Thanks for the response, created issue there :)
