### ISSUE TITLE
Incorrect Prism global in browser environment

### ISSUE THREAD

**Issue by thompsongl** [wooorm/refractor#52]
Related to #38, but in this case focused on browser environments. The global Prism instance is not correctly setting `manual` or `disableWorkerMessageHandler` as intended in `core.js`: https://github.com/wooorm/refractor/blob/e399dffa4017f8f2a639568fd92a408e76e7c23d/lib/core.js#L59

<img width="754" alt="Screen Shot 2021-09-21 at 10 06 04 AM" src="https://user-images.githubusercontent.com/2728212/134199158-32f63506-ed4e-478d-ab35-69f89b6b4013.png">

The result is that `code` elements are automatically processed by Prism, and in my case altering the DOM in an unwanted manner.

<img width="817" alt="Screen Shot 2021-09-21 at 10 05 19 AM" src="https://user-images.githubusercontent.com/2728212/134199356-c939150e-7684-45cc-8b56-98cb57a5f67a.png">

Minimal reproduction in codesandbox: https://codesandbox.io/s/stoic-mccarthy-9fjzr?file=/src/App.js

N.B.: I think this only affects v4.x; `window.Prism` is not defined in v3.4.0

**Comment by wooorm** [comment]
- Weird that 3.4.0 is not affected? I think #38 was about #37, which is on both 3 and 4?
- Do you have an idea on how it can be solved?

**Comment by thompsongl** [comment]
Thanks for the quick reply, @wooorm!

Something as simple as

```diff
// Inherit.
function Refractor() {}

+ Prism.manual = true;
+ Prism.disableWorkerMessageHandler = true;

Refractor.prototype = Prism
```

in `core.js#L77` appears to do the trick, but I'm lacking background on the reason for the `ctx` logic.

**Comment by wooorm** [comment]
Hmm. The Prism code is a bit complex to read. They suggest setting `window.Prism = {manual: true}` to not auto-highlight the document.

With your technique, I’m guessing that [this line still runs](https://github.com/PrismJS/prism/blob/99d94fa7c39d5aabee38ae0e729c330146820b4d/components/prism-core.js#L1149), but [this one doesn’t](https://github.com/PrismJS/prism/blob/99d94fa7c39d5aabee38ae0e729c330146820b4d/components/prism-core.js#L1138)? 🤔

**Comment by thompsongl** [comment]
👍 I'm happy to open a PR if we all agree this is the right approach

**Comment by thompsongl** [comment]
Created #53 after confirming it fixes the browser environment problem. Happy make changes if more is needed to also resolve #38

**Comment by rexxars** [comment]
I never managed to fully isolate and reproduce #38, but the suggested fix seems logical to me
