### ISSUE TITLE
How to use multiple syntax?

### ISSUE THREAD

**Issue by ysuzuki19** [wooorm/refractor#60]
Thank you for implement great library!

I use this library within `@mapbox/rehype-prism`.

I want to multiple syntax highlight like as [`diff-typescript` or `typescript-diff`](https://prismjs.com/plugins/diff-highlight/), but it is unavailable. the log is following message.

```
Error: Unknown language: `diff-typescript` is not registered
```

In `@mapbox/rehype-prism`, run [following line](https://github.com/mapbox/rehype-prism/blob/fb4174fce30a1cde8d784fa94e7c04d8a7fa6d28/index.js#L34) with `diff-typescript`.

```javascript
      result = refractor.highlight(nodeToString(node), lang);
```

Is there a way to solve this issue like piping multiple syntax (`diff`→`typescript`)?

Thanks!

**Comment by wooorm** [comment]
You link to a Prism plugin. This project does not support Prism plugins: https://github.com/wooorm/refractor#compatibility.

You can do similar things on the AST though. Something like https://github.com/wooorm/refractor/issues/8#issuecomment-852788226.
