### ISSUE TITLE
The syntax highlighting issue when multiline comments are not closed prismjs@1.17.1

### ISSUE THREAD

**Issue by CocoaTouch123** [wooorm/refractor#70]
plugin list："dependencies": {
    "prism-themes": "1.4.0",
    "react": "16.12.0",
    "react-diff-view": "2.4.4",
    "react-dom": "16.12.0",
    "react-scripts": "3.0.1",
    "refractor": "3.0.0"
  },
codesandbox demo url ：https://codesandbox.io/p/sandbox/react-diff-view-with-code-expansion-forked-n9z7l6
Please take a look. You can reproduce it by clicking 'Expand Down' below line 190.
![image](https://github.com/user-attachments/assets/bdcec0dc-ca43-4e9b-b417-088725378584)

**Comment by wooorm** [comment]
If it’s an issue with prism, it is an issue for prism, not for refractor
