### ISSUE TITLE
Support for styling tabs

### ISSUE THREAD

**Issue by marktheminer** [wooorm/refractor#71]
I'd like to be able to highlight tabs via css in the results of react-syntax-highlighter and to do that I need to have tabs wrapped in a span.

I've got it working with these changes to core.js (in refractor 3.6.0):

![image](https://github.com/user-attachments/assets/f3ebb91f-d2bd-4420-ae85-b34785cc2337)

and

![image](https://github.com/user-attachments/assets/f125e8e3-344f-4227-b46a-d5bd0ba9a8a0)

One call site I'm unsure about with this change would be on line 183 below: 

![image](https://github.com/user-attachments/assets/b16d606a-8d3a-4337-bfa5-41f3dcc0777e)

Also, I'm curious whether this would be accepted in a PR?  I'd be interested in seeing it in 3.6.0 (so 3.7.0) as soon as I was done (as 3.6.0 is what react-syntax-highlighter currently uses), but I'm willing to make another PR for the current head of the main branch.

I confirmed with the react-syntax-highlighter demo that I do get exactly what I want with this change.

As a diff, that is:

```diff --git a/core.js b/core.js
index 17dd816..5f82339 100644
--- a/core.js
+++ b/core.js
@@ -152,7 +152,26 @@ function stringify(value, language, parent) {
   var env

   if (typeof value === 'string') {
-    return {type: 'text', value: value}
+    var parts = value.split(/(?<!\\)\t/)
+    if (parts.length === 1) {
+      return {type: 'text', value}
+    } else {
+      debugger
+      /** @type {Array<Text|RefractorElement>} */
+      var result = []
+      parts.forEach((p, i) => {
+        result.push({type: 'text', value: p})
+        if (i < parts.length - 1) {
+          result.push({
+            type: 'element',
+            tagName: 'span',
+            properties: {className: ['tab']},
+            children: [{type: 'text', value: '\t'}]
+          })
+        }
+      })
+      return result
+    }
   }

   if (refract.util.type(value) === 'Array') {
@@ -198,13 +217,18 @@ function stringifyAll(values, language) {

   index = -1
   length = result.length
-
+  var finalResult = []
   while (++index < length) {
     value = result[index]
-    result[index] = refract.Token.stringify(value, language, result)
+    var stringified = refract.Token.stringify(value, language, result)
+    if (refract.util.type(stringified) === 'Array') {
+      stringified.forEach((s) => finalResult.push(s))
+    } else {
+      finalResult.push(stringified)
+    }
   }

-  return result
+  return finalResult
 }

 function encode(tokens) {
````

**Comment by marktheminer** [comment]
@wooorm how would you feel about this as a PR?  Does it fit the standard you have tried to meet, or is it outside of it and therefore no appropriate for general release?

**Comment by wooorm** [comment]
Hi!

Thanks but no thanks. This doesn’t fit with this project. This project is about grammars and syntax highlighting and matching Prism. It doesn’t do other things.

This project gives back an AST, which you can change. No need to fork: it’s all made to be extendable.

You could use [`hast-util-find-and-replace`](https://github.com/syntax-tree/hast-util-find-and-replace) to regex that tree. Or manually, it shouldn’t be too hard.
